/** The domain: a free-form ledger validated by `mutate`, summed up by the derived functions.
 *  The code lives in src/lib/store/; this file is its public API, unchanged by the split. */
export {
  type Role,
  type ActingRole,
  type Values,
  type EntryKind,
  type Entry,
  type Lot,
  type Database,
  roleName,
  entryBy,
  materials,
  branches,
  batchKinds,
  branchMeatKinds,
  titles,
  editDecisions,
  editLockedKeys,
  unpack,
  seed,
} from "./store/model";
export {
  n,
  entries,
  produced,
  producedBags,
  packWeights,
  validPackWeights,
  processed,
  lotProgress,
  centralStock,
  rawAtFoodiva,
  readyForChefHouse,
  purchaseLots,
  shipmentLines,
  shipments,
  awaitingReturn,
  drawnKg,
  poRemainingKg,
  latestPackingList,
  packingListKg,
  shipmentShares,
  shipmentChain,
  reservedForOwnerContent,
  ownerWasteReceived,
  ownerWasteOutstanding,
  preSmokeTrimKg,
  rawAtSmoker,
  pendingSmokeKg,
  processLoss,
  averageYield,
  offShelf,
  balance,
  branchMeatDay,
  packWeightWarning,
  allocationOutstanding,
  pendingReceiveKg,
  riceSources,
  cooksRice,
  requiredRiceKinds,
  closeDayChecklist,
  type CloseDayItem,
  rawRiceStock,
  issuedRawRiceStock,
  cookedRiceStock,
  chiliAllocated,
  ownerChiliStock,
  chiliSold,
  chiliStock,
  ownerMaterialStock,
  branchMaterialStock,
  materialPar,
  materialUnitPrice,
  isClosed,
  lotCost,
  saleCost,
  unlinkedSummary,
  smokeServiceRate,
  smokingInvoiceStatus,
  smokingInvoiceReview,
  smokingInvoiceRejection,
  currentSmokingInvoices,
  ownerPendingInvoices,
  revenue,
} from "./store/derived";
export {
  saleMoneyKeys,
  visibleLots,
  visibleEntries,
  visibleDatabase,
  editBlock,
  openEditRequest,
  entryEdits,
  editRequestRows,
} from "./store/visibility";
export {
  packingListBoxes,
  receivedBoxWeights,
  check,
  mutate,
  recordRole,
  dispatchWithPackingList,
  saleWithInfluencers,
} from "./store/mutate";
