/** The domain: a free-form ledger validated by `mutate`, summed up by the derived functions.
 *  The code lives in src/lib/store/; this file is its public API. */
export {
  type Role,
  type ActingRole,
  type Actor,
  type Values,
  type EntryKind,
  type NoteKind,
  type Entry,
  type Lot,
  type Database,
  type Channel,
  type Material,
  type PayCategory,
  entryKinds,
  noteKinds,
  isNoteKind,
  coreLotKinds,
  kindInfo,
  retiredKinds,
  roleName,
  entryBy,
  branches,
  batchKinds,
  titles,
  editableKinds,
  voidableKinds,
  editLockedKeys,
  lotMovableKinds,
  changeKinds,
  canChange,
  isEditOverlay,
  missingKeys,
  missingText,
  unpack,
  salesChannels,
  materialList,
  payCategories,
  payrollCategory,
  rentCategory,
  capexCategory,
  stockCategories,
  branchCategories,
  ingredients,
  companyPayer,
  seed,
} from "./store/model";
export {
  n,
  sum,
  decimal,
  isVoided,
  entries,
  liveEntries,
  liveLots,
  purchaseLots,
  shipments,
  byDateAt,
  packWeights,
  saleMoney,
  type Outflow,
  outflows,
  type MonthPl,
  monthPl,
  type LotInfo,
  lotInfo,
  boxCost,
  poInfo,
  meatUsedKg,
  branchMeat,
  branchMaterial,
  branchChili,
  type SupplierBalance,
  supplierBalances,
  advances,
  giftBoxes,
  hasSale,
} from "./store/derived";
export {
  saleMoneyKeys,
  isSaleMoneyKey,
  managerHidden,
  visibleEntries,
  visibleNotes,
  editBlock,
  voidBlock,
  entryEdits,
  type Todo,
  todos,
} from "./store/visibility";
export { mutate, recordRole } from "./store/mutate";
