// ponytail: PO_CSS is a minified copy of src/styles/print-document.css (the on-screen PO preview), because the
// print popup can't load the app stylesheet. A `?raw` import of the .css file would remove the copy, but
// Next 16 only documents `?raw` for import.meta.glob, so it stays a string. Change both together.
export const PO_CSS = `.po-paper{max-width:540px;min-height:700px;margin:0 auto;padding:36px;background:#fff;color:#0f172a;box-shadow:0 10px 30px rgba(15,23,42,.14)}.po-paper-heading{display:flex;justify-content:space-between;gap:18px;padding-bottom:22px;border-bottom:2px solid #2563eb}.po-brand-block{display:flex;align-items:flex-start;gap:12px;min-width:0}.po-logo{display:block;width:48px;height:48px;flex:0 0 48px;border-radius:10px;object-fit:contain;border:1px solid #e2e8f0;background:#fff}.po-paper h3{margin:5px 0 0;color:#2563eb;font-size:25px;font-weight:700;line-height:normal;letter-spacing:.02em}.po-number{min-width:145px;text-align:right}.po-number span,.po-party-grid section>span,.po-meta-grid span,.po-note>strong{display:block;font-size:10px;color:#64748b;text-transform:uppercase;letter-spacing:.04em}.po-number strong{display:block;margin-top:6px;color:#0f172a;font-size:12px}.po-party-grid{display:grid;grid-template-columns:1fr 1fr;gap:24px;padding:24px 0}.po-party-grid section{min-width:0}.po-party-grid strong{display:block;margin:7px 0;font-size:14px}.po-party-grid p{margin:3px 0;color:#64748b;font-size:11px;line-height:1.55;overflow-wrap:anywhere}.po-meta-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;padding:14px 0;border-top:1px solid #e2e8f0;border-bottom:1px solid #e2e8f0}.po-meta-grid strong{display:block;margin-top:5px;font-size:11px;line-height:1.4}.po-item-table{width:100%;margin-top:22px;border-collapse:collapse;font-size:11px}.po-item-table th{padding:10px 8px;border-bottom:1px solid #e2e8f0;color:#64748b;font-size:10px;font-weight:600;text-align:left;white-space:nowrap}.po-item-table td{padding:12px 8px;border-bottom:1px solid #e2e8f0;line-height:1.45;vertical-align:top}.po-item-table th:nth-child(n+3),.po-item-table td:nth-child(n+3){text-align:right;white-space:nowrap}.po-rate-note{margin-top:14px;padding:10px 12px;background:#f8fafc;border-left:3px solid #64748b;color:#64748b;font-size:10px;line-height:1.55}.po-total{display:flex;justify-content:flex-end;align-items:baseline;gap:26px;margin-top:20px;color:#0f172a}.po-total span{font-size:12px;font-weight:600}.po-total strong{font-size:19px}.po-note{margin-top:28px;padding-top:16px;border-top:1px solid #e2e8f0}.po-note p{min-height:22px;margin:7px 0 0;color:#64748b;font-size:11px;line-height:1.55;white-space:pre-line}.po-paper-footer{display:flex;justify-content:space-between;gap:14px;margin-top:46px;padding-top:12px;border-top:1px solid #e2e8f0;color:#64748b;font-size:10px}`;

// The on-screen paper is 540px wide; zoom 1.46 scales it to the A4 width (210mm ≈ 794px) when printing.
export const PO_PAGE_CSS = `@page{size:A4;margin:0}*{box-sizing:border-box}body{margin:0;padding:22px;background:#f8fafc;font-family:'Noto Sans Thai',Arial,sans-serif}@media print{body{padding:0;background:#fff}.po-paper{zoom:1.46;min-height:0;box-shadow:none}}${PO_CSS}`;

/** Generic key/value document sheet; only used inside the print popup. */
export const SHEET_CSS = `@page{size:A4;margin:0}*{box-sizing:border-box}body{margin:0;background:#e9eee7;font-family:'Noto Sans Thai',Arial,sans-serif;color:#18342e}.sheet{width:210mm;min-height:297mm;margin:0 auto;padding:23mm 20mm;background:#fff}.head{display:flex;justify-content:space-between;gap:20px;padding-bottom:18mm;border-bottom:2px solid #315f4d}.head h1{margin:0;color:#165846;font-size:30px;letter-spacing:.04em}.number{text-align:right}.number span{display:block;color:#617b70;font-size:11px;letter-spacing:.04em}.number strong{display:block;margin-top:8px;color:#174d3f;font-size:15px}.details{width:100%;margin-top:18mm;border-collapse:collapse;font-size:12px}.details th,.details td{padding:12px;border:1px solid #d6e0da;text-align:left}.details th{width:38%;background:#f1f5ef;color:#365d4b}.footer{display:flex;justify-content:space-between;gap:16px;margin-top:32mm;padding-top:12px;border-top:1px solid #d7e0da;color:#718078;font-size:11px}@media print{body{background:#fff}.sheet{margin:0;width:auto;min-height:auto}}`;
